### ISSUE TITLE
Refresh removes all my chats, errors in console

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/digitaltwin#39]
![image](https://user-images.githubusercontent.com/59569757/107242488-527d9800-6a2c-11eb-9d55-0706aa83fc7b.png)

**Comment by ken-de-moor** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: ENOTDIR: not a directory, open &#39;/appdata/chats/chat.json/chat.json&#39;<br> &nbsp; &nbsp;at Object.openSync (node:fs:492:3)<br> &nbsp; &nbsp;at Object.readFileSync (node:fs:393:35)<br> &nbsp; &nbsp;at Object.getChat (/backend/dist/src/service/dataService.js:19:42)<br> &nbsp; &nbsp;at /backend/dist/src/service/chatService.js:27:40<br> &nbsp; &nbsp;at Array.map (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at Object.getAcceptedChats (/backend/dist/src/service/chatService.js:27:10)<br> &nbsp; &nbsp;at /backend/dist/src/routes/chats.js:22:39<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/backend/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/backend/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/backend/node_modules/express/lib/router/route.js:112:3)</pre>
</body>
</html>
